time ./nih -tech_lef benchmarks/des_perf_b_md1/tech.lef -cell_lef benchmarks/des_perf_b_md1/cells_modified.lef -input_def benchmarks/des_perf_b_md1/placed.def -cpu 1 -placement_constraints benchmarks/des_perf_b_md1/placement.constraints

time ./nih -tech_lef benchmarks/fft_a_md2/tech.lef -cell_lef benchmarks/fft_a_md2/cells_modified.lef -input_def benchmarks/fft_a_md2/placed.def -cpu 1 -placement_constraints benchmarks/fft_a_md2/placement.constraints 

time ./nih -tech_lef benchmarks/pci_bridge32_a_md1/tech.lef -cell_lef benchmarks/pci_bridge32_a_md1/cells_modified.lef -input_def benchmarks/pci_bridge32_a_md1/placed.def -cpu 1 -placement_constraints benchmarks/pci_bridge32_a_md1/placement.constraints 

time ./nih -tech_lef benchmarks/pci_bridge32_b_md1/tech.lef -cell_lef benchmarks/pci_bridge32_b_md1/cells_modified.lef -input_def benchmarks/pci_bridge32_b_md1/placed.def -cpu 1 -placement_constraints benchmarks/pci_bridge32_b_md1/placement.constraints 

time ./nih -tech_lef benchmarks/pci_bridge32_b_md2/tech.lef -cell_lef benchmarks/pci_bridge32_b_md2/cells_modified.lef -input_def benchmarks/pci_bridge32_b_md2/placed.def -cpu 1 -placement_constraints benchmarks/pci_bridge32_b_md2/placement.constraints 

time ./nih -tech_lef benchmarks/pci_bridge32_b_md3/tech.lef -cell_lef benchmarks/pci_bridge32_b_md3/cells_modified.lef -input_def benchmarks/pci_bridge32_b_md3/placed.def -cpu 1 -placement_constraints benchmarks/pci_bridge32_b_md3/placement.constraints 

time ./nih -tech_lef benchmarks/pci_bridge32_a_md2/tech.lef -cell_lef benchmarks/pci_bridge32_a_md2/cells_modified.lef -input_def benchmarks/pci_bridge32_a_md2/placed.def -cpu 1 -placement_constraints benchmarks/pci_bridge32_a_md2/placement.constraints 

time ./nih -tech_lef benchmarks/des_perf_a_md1/tech.lef -cell_lef benchmarks/des_perf_a_md1/cells_modified.lef -input_def benchmarks/des_perf_a_md1/placed.def -cpu 1 -placement_constraints benchmarks/des_perf_a_md1/placement.constraints 

time ./nih -tech_lef benchmarks/des_perf_a_md2/tech.lef -cell_lef benchmarks/des_perf_a_md2/cells_modified.lef -input_def benchmarks/des_perf_a_md2/placed.def -cpu 1 -placement_constraints benchmarks/des_perf_a_md2/placement.constraints 

time ./nih -tech_lef benchmarks/fft_a_md3/tech.lef -cell_lef benchmarks/fft_a_md3/cells_modified.lef -input_def benchmarks/fft_a_md3/placed.def -cpu 1 -placement_constraints benchmarks/fft_a_md3/placement.constraints 

time ./nih -tech_lef benchmarks/des_perf_b_md2/tech.lef -cell_lef benchmarks/des_perf_b_md2/cells_modified.lef -input_def benchmarks/des_perf_b_md2/placed.def -cpu 1 -placement_constraints benchmarks/des_perf_b_md2/placement.constraints 

time ./nih -tech_lef benchmarks/edit_dist_a_md3/tech.lef -cell_lef benchmarks/edit_dist_a_md3/cells_modified.lef -input_def benchmarks/edit_dist_a_md3/placed.def -cpu 1 -placement_constraints benchmarks/edit_dist_a_md3/placement.constraints 


time ./nih -tech_lef benchmarks/des_perf_1/tech.lef -cell_lef benchmarks/des_perf_1/cells_modified.lef -input_def benchmarks/des_perf_1/placed.def -cpu 1 -placement_constraints benchmarks/des_perf_1/placement.constraints 

time ./nih -tech_lef benchmarks/edit_dist_a_md2/tech.lef -cell_lef benchmarks/edit_dist_a_md2/cells_modified.lef -input_def benchmarks/edit_dist_a_md2/placed.def -cpu 1 -placement_constraints benchmarks/edit_dist_a_md2/placement.constraints 

time ./nih -tech_lef benchmarks/fft_2_md2/tech.lef -cell_lef benchmarks/fft_2_md2/cells_modified.lef -input_def benchmarks/fft_2_md2/placed.def -cpu 1 -placement_constraints benchmarks/fft_2_md2/placement.constraints 

time ./nih -tech_lef benchmarks/edit_dist_1_md1/tech.lef -cell_lef benchmarks/edit_dist_1_md1/cells_modified.lef -input_def benchmarks/edit_dist_1_md1/placed.def -cpu 1 -placement_constraints benchmarks/edit_dist_1_md1/placement.constraints 

